mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('job1app.urls')),
    path('accounts/', include('users.urls')),
    path('contact', include('contact.urls')),
    path('subscriber/', include('subscriber.urls')),
    path('salaries/', include('salaries.urls')),
    path('company/', include('company.urls')),
    # path('accounts/', include('allauth.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.index_title = "HAMRO JAGIR"
admin.site.site_header = "HAMRO JAGIR"
admin.site.site_title = "HAMRO JAGIR"

salaries/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.SalariesListView.as_view(), name='salaries')
]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import (user_register, account_activate, LogoutView, check_email)
from .forms import UserLoginForm

urlpatterns = [
    path('register/', user_register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/registration/login.html',
                                        form_class=UserLoginForm), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('activate/<slug:uidb64>/<slug:token>)/', account_activate, name='activate'),
]

htmx_urlpatterns = [
    path('check_email/', check_email, name='check_email')
]

urlpatterns += htmx_urlpatterns

salaries/models.py
from django.db import models


class Salary(models.Model):
    POSITION_JUNIOR = 'jr'
    POSITION_SENIOR = 'sr'
    POSITION_ASSOCIATE = 'as'
    POSITION_MANAGER = 'mgr'
    POSITION_LEAD = 'ld'

    POSITION_CHOICES = (
        (POSITION_JUNIOR, 'Junior'),
        (POSITION_SENIOR, 'Senior'),
        (POSITION_ASSOCIATE, 'Associate'),
        (POSITION_MANAGER, 'Manager'),
        (POSITION_LEAD, 'Lead')
    )

    EMPLOYEE_STATUS_CURRENT = 'crnt'
    EMPLOYEE_STATUS_EX = 'ex'

    EMPLOYEE_STATUS_CHOICES = (
        (EMPLOYEE_STATUS_CURRENT, 'Current Employee'),
        (EMPLOYEE_STATUS_EX, 'Ex Employee')
    )

    EXPERIENCE_ZERO = '0'
    EXPERIENCE_ONE = '1'
    EXPERIENCE_TWO = '2'
    EXPERIENCE_THREE = '3'
    EXPERIENCE_FOUR = '4'
    EXPERIENCE_FIVE = '5'
    EXPERIENCE_SIX = '6'
    EXPERIENCE_SEVEN = '7'
    EXPERIENCE_EIGHT = '8'
    EXPERIENCE_NINE = '9'
    EXPERIENCE_TEN = '10'
    EXPERIENCE_TEN_PLUS = '10+'

    YEAR_OF_EXPERIENCE_CHOICES = (
        (EXPERIENCE_ZERO, '0'),
        (EXPERIENCE_ONE, '1'),
        (EXPERIENCE_TWO, '2'),
        (EXPERIENCE_THREE, '3'),
        (EXPERIENCE_FOUR, '4'),
        (EXPERIENCE_FIVE, '5'),
        (EXPERIENCE_SIX, '6'),
        (EXPERIENCE_SEVEN, '7'),
        (EXPERIENCE_EIGHT, '8'),
        (EXPERIENCE_NINE, '9'),
        (EXPERIENCE_TEN, '10'),
        (EXPERIENCE_TEN_PLUS, '10+')
    )

    GENDER_MALE = 'ml'
    GENDER_FEMALE = 'fml'
    GENDER_OTHER = 'othr'

    GENDER_CHOICES = (
        (GENDER_MALE, 'Male'),
        (GENDER_FEMALE, 'Female'),
        (GENDER_OTHER, 'Other')
    )
    role = models.CharField(max_length=255)
    salary = models.IntegerField()
    company_name = models.CharField(verbose_name='Company', max_length=255)
    company_website = models.URLField(verbose_name='Company Website')
    position = models.CharField(choices=POSITION_CHOICES, max_length=3)
    employee_status = models.CharField(verbose_name='Employee Status', choices=EMPLOYEE_STATUS_CHOICES, max_length=4)
    experience = models.CharField(verbose_name='Years Of Experience', choices=YEAR_OF_EXPERIENCE_CHOICES, max_length=3)
    gender = models.CharField(choices=GENDER_CHOICES, max_length=4)

    def __str__(self):
        return f'Salary Info {self.id}'

    class Meta:
        ordering = ('-id',)

salaries/forms.py
from django import forms

from .models import Salary


class SalaryModelForm(forms.ModelForm):
    class Meta:
        model = Salary
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(SalaryModelForm, self).__init__(*args, **kwargs)
        self.fields['role'].widget.attrs.update({'class': 'form-control mb-3'})
        self.fields['salary'].widget.attrs.update({'class': 'form-control mb-3'})
        self.fields['company_name'].widget.attrs.update({'class': 'form-control mb-3'})
        self.fields['company_website'].widget.attrs.update({'class': 'form-control mb-3'})
        self.fields['position'].widget.attrs.update({'class': 'form-control mb-3'})
        self.fields['employee_status'].widget.attrs.update({'class': 'form-control mb-3'})
        self.fields['experience'].widget.attrs.update({'class': 'form-control mb-3'})
        self.fields['gender'].widget.attrs.update({'class': 'form-control mb-3'})

salaries/views.py
from django.shortcuts import render
from django.views.generic import CreateView, ListView
from django.contrib import messages
from django.urls import reverse_lazy
from django.core.paginator import Paginator

from .models import Salary
from .forms import SalaryModelForm


class SalariesListView(CreateView):
    model = Salary
    template_name = 'salaries/salaries.html'
    form_class = SalaryModelForm
    success_url = reverse_lazy('salaries')

    def get_context_data(self, **kwargs):
        context = super(SalariesListView, self).get_context_data(**kwargs)
        context['salaries'] = Salary.objects.all()
        page = self.request.GET.get('page')
        paginator = Paginator(context['salaries'], 6)
        context['page_obj'] = paginator.get_page(page)
        return context

    def form_valid(self, form):
        form = super(SalariesListView, self).form_valid(form)
        messages.add_message(self.request, messages.SUCCESS, "Your job posted successfully!")
        return form

templates/salaries/salaries.html
{% extends 'base.html' %}
{% load humanize %}

{% block title %}

{% endblock %}



{% block content %}

    <div class="container my-5">


        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <div class="alert alert-success alert-dismissible fade show" role="alert">
             <li style="list-style-type: none;" {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>

                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>

            {% endfor %}
        </ul>
    {% endif %}


        <div class="post-salary text-center">
            <h3 class="text-center">Post your salary anonymously</h3>
            <p style="width: 80%; margin: 0 auto; text-align: center;">Your small steps makes huge impact in the community.🙌 Disclose your salary anonymously and help to bring transparency in the market.😇😇</p>
        </div>
        <div style="display: flex; justify-content: center">
        <button class="btn  btn-primary my-3" type="button" data-bs-toggle="modal" data-bs-target="#salary">Post salary anonymously</button>
        </div>
        {% include 'salaries/utils/salary-post.html' %}


    <div class="container card-wrapper my-3">

    {% for salary in page_obj %}

        <div class="card my-card">
                <div class="card-title text-center mt-3"><h6 style="font-family: Monospace; font-size: 20px;">{{ salary.role|upper }}</h6></div>

                <div class="card-body">
                    <div class="mb-3">
                        <h6 style="font-weight: bold;">Salary</h6>
                        <b style="color:#2FC86B">Rs {{ salary.salary|intcomma }} per month</b>
                    </div>

                    <div>
                        <h6 style="font-weight: bold; margin: 0;">Company</h6>
                        <p style="font-weight: 600;" class="text-primary company_website">
                            <a href="{{ salary.company_website }}"
                               target="_blank"
                               style="text-decoration: none;">{{ salary.company_name|title }}</a></p>
                    </div>

                    <div>
                        <h6 style="font-weight: bold; margin: 0;">Position</h6>
                        <p style="font-weight: 600;">{{ salary.get_position_display|title }}</p>
                    </div>

                    <div>
                        <h6 style="font-weight: bold; margin: 0;">Employee Status</h6>
                        <p style="font-weight: 600;">{{ salary.get_employee_status_display|title }}</p>
                    </div>

                    <div>
                        <h6 style="font-weight: bold; margin: 0;">Years of experience</h6>
                        <p style="font-weight: 600;">{{ salary.get_experience_display|title }}</p>
                    </div>

                    <div>
                        <h6 style="font-weight: bold; margin: 0;">Gender</h6>
                        <p style="font-weight: 600;">{{ salary.get_gender_display|title }}</p>
                    </div>


                </div>


        </div>

    {% endfor %}

    <nav aria-label="Page navigation example">
  <ul class="pagination">

        {% if page_obj.has_previous %}
            <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
            <span class="sr-only">Previous</span>
            </a>
            </li>
        {% endif %}

  {% for i in page_obj.paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="active page-item"><span class="page-link">{{ i }} </span></li>
      {% else %}
        <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
        <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
        <span class="sr-only">Next</span>
      </a>
    </li>
    {% endif %}

  </ul>
</nav>

    </div>


{% endblock %}