job1app/urls.py
from django.urls import path
from .views import (HomeView, JobCategoryView,
                    apply, InternshipCategoryView, search,
                    JobList, JobDetailView)

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('detail/<slug:slug>', JobDetailView.as_view(), name="job-detail"),
    path('apply/', apply, name='apply'),
    path('jobs/', JobCategoryView.as_view(), name='job-category'),
    path('internships/', InternshipCategoryView.as_view(), name='internship-category'),
    path('search/', search, name='search'),
    path('job-list/', JobList.as_view(), name='job-list'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('job1app.urls')),
    path('accounts/', include('users.urls')),
    path('contact', include('contact.urls')),
    path('subscriber/', include('subscriber.urls')),
    path('salaries/', include('salaries.urls')),
    path('company/', include('company.urls')),
    # path('accounts/', include('allauth.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.index_title = "HAMRO JAGIR"
admin.site.site_header = "HAMRO JAGIR"
admin.site.site_title = "HAMRO JAGIR"

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import (user_register, account_activate, LogoutView, check_email)
from .forms import UserLoginForm

urlpatterns = [
    path('register/', user_register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/registration/login.html',
                                        form_class=UserLoginForm), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('activate/<slug:uidb64>/<slug:token>)/', account_activate, name='activate'),
]

htmx_urlpatterns = [
    path('check_email/', check_email, name='check_email')
]

urlpatterns += htmx_urlpatterns

job1app/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse
from django.contrib.contenttypes.models import ContentType

from taggit.managers import TaggableManager
from ckeditor.fields import RichTextField


class JobActiveManager(models.Manager):
    def get_queryset(self):
        return super(JobActiveManager, self).get_queryset().filter(is_active=True)


class Category(models.Model):
    """
    here we define what type of work is it
    """
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Job(models.Model):
    job_type = (
        ('non remote', 'non remote'),
        ('remote', 'remote')
    )
    title = models.CharField(max_length=500)
    slug = models.SlugField(blank=True, null=True)
    apply_before = models.DateField(verbose_name='apply before', null=True, blank=True)
    education_level = models.CharField(verbose_name='education level', max_length=255, blank=True, null=True)
    no_of_vacancy = models.CharField(verbose_name='number of vacancy', max_length=255, blank=True, null=True)
    experience = models.CharField(max_length=255, null=True, blank=True)
    specification = RichTextField(verbose_name='job specification', blank=True)
    requirement = RichTextField(verbose_name='technical requirement', blank=True, null=True)
    benefit = RichTextField(blank=True, null=True)
    category = models.ForeignKey(Category, related_name='category', on_delete=models.CASCADE)
    organization = models.CharField(max_length=255, blank=True, null=True)
    location = models.CharField(max_length=255, blank=True, null=True)
    salary = models.CharField(max_length=255, blank=True, null=True)
    work_day = models.IntegerField(default=6)
    type = models.CharField(max_length=20, choices=job_type, default='non remote')
    # for internship
    is_paid = models.BooleanField(default=True, help_text="for internship only")
    duration = models.CharField(max_length=255, blank=True, null=True, help_text="for internship only")
    additional_benefits = models.BooleanField(blank=True, null=True)
    tags = TaggableManager()
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    objects = models.Manager()
    active = JobActiveManager()

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title+" " + self.organization)
        return super().save(*args, **kwargs)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('job-detail', kwargs={'slug': self.slug})

job1app/forms.py
from django import forms

from .models import Job

class DateInput(forms.DateInput):
    input_type = 'date'


class JobForm(forms.ModelForm):
    class Meta:
        model = Job
        exclude = ('slug', )
        widgets = {
            'apply_before': DateInput()
        }

    def __init__(self, *args, **kwargs):
        super(JobForm, self).__init__(*args, **kwargs)
        self.fields['title'].widget.attrs.update({'class': 'form-control mb-3'})
        self.fields['apply_before'].widget.attrs.update({'class': 'form-control mb-3'})
        self.fields['education_level'].widget.attrs.update({'class': 'form-control mb-3'})
        self.fields['no_of_vacancy'].widget.attrs.update({'class': 'form-control mb-3'})
        self.fields['experience'].widget.attrs.update({'class': 'form-control mb-3'})
        self.fields['specification'].widget.attrs.update({'class': 'form-control mb-3'})
        self.fields['requirement'].widget.attrs.update({'class': 'form-control mb-3'})
        self.fields['benefit'].widget.attrs.update({'class': 'form-control mb-3'})
        self.fields['category'].widget.attrs.update({'class': 'form-control mb-3'})
        self.fields['organization'].widget.attrs.update({'class': 'form-control mb-3'})
        self.fields['location'].widget.attrs.update({'class': 'form-control mb-3'})
        self.fields['salary'].widget.attrs.update({'class': 'form-control mb-3'})
        self.fields['work_day'].widget.attrs.update({'class': 'form-control mb-3'})
        self.fields['type'].widget.attrs.update({'class': 'form-control mb-3'})
        self.fields['is_paid'].widget.attrs.update({'class': ' mb-3'})
        self.fields['duration'].widget.attrs.update({'class': 'form-control mb-3'})
        self.fields['benefit'].widget.attrs.update({'class': 'form-control mb-3'})
        self.fields['tags'].widget.attrs.update({'class': 'form-control mb-3'})
        self.fields['is_active'].widget.attrs.update({'class': ' mb-3'})

job1app/views.py
from django.conf import settings
from django.contrib import messages
from django.core.files.storage import FileSystemStorage
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.template.loader import render_to_string
from django.views.generic import (TemplateView, ListView, DetailView)
from django.core.paginator import Paginator

from taggit.models import Tag
from rest_framework.generics import ListAPIView

from .models import Category, Job
from .tasks import send_email
from .serializers import JobSerializer


class HomeView(ListView):
    template_name = 'job1app/home.html'
    context_object_name = 'jobs'
    model = Job

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        context['tags'] = Tag.objects.all()
        return context


class JobList(ListAPIView):
    queryset = Job.active.all()
    serializer_class = JobSerializer


class JobCategoryView(ListView):
    template_name = 'job1app/job_category.html'
    context_object_name = 'jobs'
    paginate_by = 5

    def get_queryset(self):
        return Job.objects.filter(category__name='Job', is_active=True)


class InternshipCategoryView(ListView):
    template_name = 'job1app/internship_category.html'
    context_object_name = 'internships'
    paginate_by = 5

    def get_queryset(self):
        return Job.objects.filter(category__name='Internship', is_active=True)


class JobDetailView(DetailView):
    model = Job
    context_object_name = 'job'
    template_name = 'job1app/job_detail.html'


def apply(request):
    if request.method == "POST" and request.FILES['file']:
        slug = request.POST.get('apply')
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        email = request.POST.get('email')
        file = request.FILES['file']

        context = {'first_name': first_name, 'last_name': last_name, 'email': email, 'slug': slug}
        message = render_to_string('mail_apply.html', context)
        email_from = settings.EMAIL_HOST_USER

        # email = EmailMessage('New application received', message, email_from,
        #                      [settings.EMAIL_TO], headers={'Reply-To': email_from})
        fs = FileSystemStorage()
        f = fs.save(file.name, file)
        fileurl = fs.url(f)
        print(fileurl)
        filename = file.name
        extension = filename.split('.')
        if extension[1] != 'txt' and extension[1] != 'pdf' and extension[1] != 'text':
            print(type(extension[1]))
            messages.add_message(request, messages.ERROR, "Not an appropriate file format!")
            return redirect('job-detail', slug=slug)
        send_email.delay(email_from, message, fileurl)
        messages.add_message(request, messages.SUCCESS, "Application send successfully!")
        return redirect('job-detail', slug=slug)

    return render(request, 'job1app/job_detail.html')


def search(request):
    home_search_text = request.GET.get('q')
    print(home_search_text)
    if home_search_text:
        qs = Job.objects.filter(title__icontains=home_search_text)

    job_category_text = request.GET.get('r')
    if job_category_text:
        job_category = Category.objects.get(name='job')
        qs = job_category.category.filter(title__icontains=job_category_text)

    internship_category_text = request.GET.get('s')
    if internship_category_text:
        internship_category = Category.objects.get(name='internship')
        qs = internship_category.category.filter(title__icontains=internship_category_text)

    return render(request, 'job1app/search.html', {'qs': qs})

templates/job1app/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <div class="container"
         x-data="{ tag:'ALL', jobs:[]}"
         x-init="jobs = await (await fetch('/job-list')).json()"
    >

    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                {% if message.tags == "warning" %}
                    <div class="alert alert-danger" style="width: 100%;">
             <li style="list-style-type: none;" {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>

</div>

                {% endif %}


            {% endfor %}
        </ul>
    {% endif %}


      <form action="{% url 'search' %}" class="m-3">
          <input type="text" name="q" id="" class="form-control" style="width: 70%;" placeholder="search...">
      </form>
{#    {% include 'job1app/search-hx.html' %}#}

    {% for tag in tags %}
        <button type="button" class="btn btn-primary btn-sm" @click="tag = $el.textContent">{{ tag.name }}</button>
    {% endfor %}
        <button type="button" class="btn btn-primary btn-sm" @click="tag = $el.textContent">ALL</button>



      <main class="m-3">
          <div class="col-md-12" style="">
        {% include 'job1app/job_list.html' %}
              {% include 'job1app/search_result.html' %}
        <section  class="col-md-5 main-right-section" style="background-color: blue";>

        </section>

    </div>

      </main>

    </div>



    {% include 'subscriber/subscriber_form.html' %}


{% endblock %}

templates/job1app/internship_category.html
{% extends 'base.html' %}

{% block title %} internships {% endblock title %}


{% block content %}

<div class="container">

      <form action="{% url 'search' %}" class="m-3">
          <input type="text" name="s" id="" class="form-control" style="width: 70%;" placeholder="search...">
      </form>

      <main>

          <div class="col-md-12" style="display: flex;">
        <section class="col-md-7 main-left-section" style=";">

            {% for job in internships %}
                <a href="{{ job.get_absolute_url }}" class="list">
                <div class="m-4 border p-3">
                <h4>{{ job.title|title }} </h4>
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-building" viewBox="0 0 16 16">
  <path fill-rule="evenodd" d="M14.763.075A.5.5 0 0 1 15 .5v15a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5V14h-1v1.5a.5.5 0 0 1-.5.5h-9a.5.5 0 0 1-.5-.5V10a.5.5 0 0 1 .342-.474L6 7.64V4.5a.5.5 0 0 1 .276-.447l8-4a.5.5 0 0 1 .487.022zM6 8.694 1 10.36V15h5V8.694zM7 15h2v-1.5a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 .5.5V15h2V1.309l-7 3.5V15z"/>
  <path d="M2 11h1v1H2v-1zm2 0h1v1H4v-1zm-2 2h1v1H2v-1zm2 0h1v1H4v-1zm4-4h1v1H8V9zm2 0h1v1h-1V9zm-2 2h1v1H8v-1zm2 0h1v1h-1v-1zm2-2h1v1h-1V9zm0 2h1v1h-1v-1zM8 7h1v1H8V7zm2 0h1v1h-1V7zm2 0h1v1h-1V7zM8 5h1v1H8V5zm2 0h1v1h-1V5zm2 0h1v1h-1V5zm0-2h1v1h-1V3z"/>
                </svg><span class="p-1 m-1"><b>{{ job.organization|title }}</b></span> <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-geo-alt-fill" viewBox="0 0 16 16">
  <path d="M8 16s6-5.686 6-10A6 6 0 0 0 2 6c0 4.314 6 10 6 10zm0-7a3 3 0 1 1 0-6 3 3 0 0 1 0 6z"/>
</svg><span class="p-1"><b>{{ job.location|title }}</b></span>
                </div>
            {% endfor %}
                </a>

        </section>
        <section  class="col-md-5 main-right-section" style="background-color: blue";>

        </section>

    </div>

      </main>

    <nav aria-label="Page navigation example">
  <ul class="pagination">

        {% if page_obj.has_previous %}
            <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
            <span class="sr-only">Previous</span>
            </a>
            </li>
        {% endif %}

  {% for i in page_obj.paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="active page-item"><span class="page-link">{{ i }} </span></li>
      {% else %}
        <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
        <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
        <span class="sr-only">Next</span>
      </a>
    </li>
    {% endif %}

  </ul>
</nav>


    </div>

{% endblock content %}

templates/job1app/job_category.html
{% extends 'base.html' %}

{% block title %} jobs {% endblock title %}


{% block content %}

<div class="container">

      <form action="{% url 'search' %}" class="m-3">
          <input type="text" name="r" id="" class="form-control" style="width: 70%;" placeholder="search...">
      </form>

      <main>

          <div class="col-md-12" style="display: flex;">
        <section class="col-md-7 main-left-section" style=";">

            {% for job in jobs %}
                <a href="{{ job.get_absolute_url }}" class="list">
                <div class="m-4 border p-3">
                <h4>{{ job.title|title }} </h4>
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-building" viewBox="0 0 16 16">
  <path fill-rule="evenodd" d="M14.763.075A.5.5 0 0 1 15 .5v15a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5V14h-1v1.5a.5.5 0 0 1-.5.5h-9a.5.5 0 0 1-.5-.5V10a.5.5 0 0 1 .342-.474L6 7.64V4.5a.5.5 0 0 1 .276-.447l8-4a.5.5 0 0 1 .487.022zM6 8.694 1 10.36V15h5V8.694zM7 15h2v-1.5a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 .5.5V15h2V1.309l-7 3.5V15z"/>
  <path d="M2 11h1v1H2v-1zm2 0h1v1H4v-1zm-2 2h1v1H2v-1zm2 0h1v1H4v-1zm4-4h1v1H8V9zm2 0h1v1h-1V9zm-2 2h1v1H8v-1zm2 0h1v1h-1v-1zm2-2h1v1h-1V9zm0 2h1v1h-1v-1zM8 7h1v1H8V7zm2 0h1v1h-1V7zm2 0h1v1h-1V7zM8 5h1v1H8V5zm2 0h1v1h-1V5zm2 0h1v1h-1V5zm0-2h1v1h-1V3z"/>
                </svg><span class="p-1 m-1"><b>{{ job.organization|title }}</b></span> <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-geo-alt-fill" viewBox="0 0 16 16">
  <path d="M8 16s6-5.686 6-10A6 6 0 0 0 2 6c0 4.314 6 10 6 10zm0-7a3 3 0 1 1 0-6 3 3 0 0 1 0 6z"/>
</svg><span class="p-1"><b>{{ job.location|title }}</b></span>
                </div>
            {% endfor %}
                </a>

        </section>
        <section  class="col-md-5 main-right-section" style="background-color: blue";>

        </section>

    </div>

      </main>

    <nav aria-label="Page navigation example">
  <ul class="pagination">

        {% if page_obj.has_previous %}
            <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
            <span class="sr-only">Previous</span>
            </a>
            </li>
        {% endif %}

  {% for i in page_obj.paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="active page-item"><span class="page-link">{{ i }} </span></li>
      {% else %}
        <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
        <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
        <span class="sr-only">Next</span>
      </a>
    </li>
    {% endif %}

  </ul>
</nav>

    </div>

{% endblock content %}

templates/job1app/job_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %} {{ job.title }} {% endblock %}

{% block content %}



    <div class="container mt-5" style="width: 70%;">
    <div class="upper-content">
        <div class="text-center">
             {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <div class="alert alert-{% if message.tags == 'error' %}danger{% endif %} alert-dismissible fade show" role="alert">
             <li style="list-style-type: none;" {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>

                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

            {% endfor %}
        </ul>
    {% endif %}


        <h3 class="mb-3">{{ job.title|title }}</h3>
        <a href="" style="text-decoration: none;"><h5>{{ job.organization|title }}</h5></a>
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-geo-alt-fill" viewBox="0 0 16 16">
  <path d="M8 16s6-5.686 6-10A6 6 0 0 0 2 6c0 4.314 6 10 6 10zm0-7a3 3 0 1 1 0-6 3 3 0 0 1 0 6z"/>
</svg>
        <span style="font-weight: bold; margin-right:15px ;">{{ job.location|title }}</span>
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-clock" viewBox="0 0 16 16">
  <path d="M8 3.5a.5.5 0 0 0-1 0V9a.5.5 0 0 0 .252.434l3.5 2a.5.5 0 0 0 .496-.868L8 8.71V3.5z"/>
  <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm7-8A7 7 0 1 1 1 8a7 7 0 0 1 14 0z"/>
</svg>
        <span style="font-weight: bold; margin-right:15px">{{ job.created|timesince }} ago</span>
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cash" viewBox="0 0 16 16">
  <path d="M8 10a2 2 0 1 0 0-4 2 2 0 0 0 0 4z"/>
  <path d="M0 4a1 1 0 0 1 1-1h14a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1H1a1 1 0 0 1-1-1V4zm3 0a2 2 0 0 1-2 2v4a2 2 0 0 1 2 2h10a2 2 0 0 1 2-2V6a2 2 0 0 1-2-2H3z"/>
</svg>
        <span style="font-weight: bold;">{{ job.salary}}</span>
        </div>
        <button class="btn btn-success mt-4 px-4" style="width: 100%;" data-bs-toggle="modal" data-bs-target="#apply"><h4>Apply</h4></button>

    </div>

<!-- Modal -->
<div class="modal fade" id="apply" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Apply</h5>
          <hr>
        <button type="button"  class="btn-close" data-bs-dismiss="modal" aria-label="Close" value="{{ job.slug }}"></button>
      </div>
      <div class="modal-body">
          <form action="{% url 'apply' %}" method="post" enctype="multipart/form-data">
              {% csrf_token %}
              <div class="row">
                  <div class="col-md-6">
              <input type="text" name="first_name" placeholder="first name" class="form-control" style="height:45px;">
                  </div>
              <div class="col-md-6">
              <input type="text" name="last_name" placeholder="last name" class="form-control" style="height: 45px">
              </div>
                  <div class="col-md-12 mt-4">
                  <input type="email" name="email" required placeholder="email" class="form-control" style="height: 45px">
                  </div>

                  <div class="col-md-12 mt-4">
                      <input type="file" required name="file" id="" class="form-control">
                  </div>
                  <div class="modal-footer">
{#                      <input type="submit" name="apply" value="{{ job.slug }}"class="btn btn-success" style="width: 100%;" value="Apply">#}
                        <button name="apply" value="{{ job.slug }}" class="btn btn-success" style="width: 100%">Apply</button>
                  </div>
              </div>
          </form>
      </div>

    </div>
  </div>
</div>


    <div class="description m-4">
        <h4 style="font-weight: bold">Description</h4>
        <hr>
        <h5 style="display: inline">Apply Before:</h5> <p style="display: inline; font-size:18px;">{{ job.apply_before }}</p><br><br>
        <h5 style="display: inline">Education Level:</h5> <p style="display: inline; font-size:18px;">{{ job.education_level }}</p><br><br>
        <h5 style="display: inline">No of Vacancy:</h5> <p style="display: inline; font-size:18px;">{{ job.no_of_vacancy }}</p><br><br>
        <h5 style="display: inline">Experience: </h5> <p style="display: inline; font-size:18px;">{{ job.experience }}</p><br><br>
        <h5>Job Specification</h5>
            {{ job.specification|safe }}<br>
        <h5>Technical Requirements</h5>
            {{ job.requirement|safe }}<br>
        <h5>Benefits</h5>
            {{ job.benefit|safe }}
    </div>
    </div>


{% endblock %}

templates/job1app/job_list.html
<section class="col-md-7 main-left-section" style="" id="content">
                <template x-for="job in jobs.filter(f => tag === 'ALL' || f.tags.includes(tag))">
                    <div style="width: 100%;">

                <a  type="button"  x-bind:href=" 'detail' + '/' + job.slug" class="list" style="display: block">
                <div class="m-4 border p-3 " >
                    <h4 x-text="job.title"></h4>
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-building" viewBox="0 0 16 16">
  <path fill-rule="evenodd" d="M14.763.075A.5.5 0 0 1 15 .5v15a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5V14h-1v1.5a.5.5 0 0 1-.5.5h-9a.5.5 0 0 1-.5-.5V10a.5.5 0 0 1 .342-.474L6 7.64V4.5a.5.5 0 0 1 .276-.447l8-4a.5.5 0 0 1 .487.022zM6 8.694 1 10.36V15h5V8.694zM7 15h2v-1.5a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 .5.5V15h2V1.309l-7 3.5V15z"/>
  <path d="M2 11h1v1H2v-1zm2 0h1v1H4v-1zm-2 2h1v1H2v-1zm2 0h1v1H4v-1zm4-4h1v1H8V9zm2 0h1v1h-1V9zm-2 2h1v1H8v-1zm2 0h1v1h-1v-1zm2-2h1v1h-1V9zm0 2h1v1h-1v-1zM8 7h1v1H8V7zm2 0h1v1h-1V7zm2 0h1v1h-1V7zM8 5h1v1H8V5zm2 0h1v1h-1V5zm2 0h1v1h-1V5zm0-2h1v1h-1V3z"/>
                </svg><span class="p-1 m-1"><b x-text="job.organization"></b></span> <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-geo-alt-fill" viewBox="0 0 16 16">
  <path d="M8 16s6-5.686 6-10A6 6 0 0 0 2 6c0 4.314 6 10 6 10zm0-7a3 3 0 1 1 0-6 3 3 0 0 1 0 6z"/>
</svg><span class="p-1"><b x-text="job.location"></b></span>
                </div>
                </a>
                        </div>
                    <br>
                        </template>
        </section>

templates/job1app/search-hx.html
<form>
        {% csrf_token %}
            <input type="text" name="q" id="" class="form-control"
                   style="width: 70%;" placeholder="search..."
                   hx-post= "{% url 'search' %}"
                   hx-trigger="keyup changed delay:500ms"
                   hx-target="#content"
            >
</form>

<div id="content"></div>

templates/job1app/search_result.html
<div id="content">
{% for job in jobs %}

    {{ job.name }}
{% endfor %}

</div>